# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: midu_read

on:
  workflow_dispatch:
  schedule:
     - cron: '*/15 1-14 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        MIDU_TOKEN: ${{ secrets.MIDU_TOKEN }}
        MIDU_TIME: ${{ secrets.MIDU_TIME }}
        MIDU_SIGN: ${{ secrets.MIDU_SIGN }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【米读自动阅读】'
        if: env.MIDU_TOKEN
        run: |
          node Task/midu_Read.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}


    
